services:
  thingsboard:
    container_name: thingsboard
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:1883:1883"
    environment:
      HTTP_BIND_PORT: 8088
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9094
      LISTENER_TCP_BIND_PORT: 1883
      SSL_ENABLED: false
    volumes:
      - ~/data/thingsboard_data/data:/data
      - ~/data/thingsboard_data/logs:/var/log/thingsboard

  kafka:
    container_name: kafka
    restart: always
    image: bitnami/kafka:3.5.2
    expose:
        - "9094"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://kafka:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker" #KRaft
      KAFKA_CFG_NODE_ID: "0" #KRaft
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #KRaft
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@127.0.0.1:9093" #KRaft
      KAFKA_CFG_LOG_RETENTION_HOURS: "48"
    volumes:
      - ~/data/kafka:/bitnami

