services:
  postgres:
    restart: always
    image: "postgres:16"
    network_mode: host
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - /mnt/tb_data/postgresdb:/var/lib/postgresql/data

  thingsboard:
    restart: always
    image: "thingsboard/tb-node:4.2.1"
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      HTTP_BIND_PORT: 8088
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: 127.0.0.1:9094
      LISTENER_TCP_BIND_PORT: 1883
      SSL_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/thingsboard
      #SPRING_DATASOURCE_USERNAME: thingsboard
    volumes:
      - /root/data/thingsboard_data/data:/data
      - /root/data/thingsboard_data/logs:/var/log/thingsboard
      - /root/data/thingsboard_config:/config

  kafka:
    restart: always
    image: "bitnamilegacy/kafka:3.5.1"
    network_mode: host
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://127.0.0.1:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker" #KRaft
      KAFKA_CFG_NODE_ID: "0" #KRaft
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #KRaft
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@127.0.0.1:9093" #KRaft
      KAFKA_CFG_LOG_RETENTION_HOURS: "48"
    volumes:
      - /root/data/kafka:/bitnami
